"""
Keyword (BM25) vs semantic (dense) retrieval on the real KO corpus.

Design rules this script follows:

1. Nothing that varies with the data is hardcoded. Stopwords are derived from
   the corpus per language, the indexed and held-out field lists are read from
   the latest field audit, and every remaining constant is a CLI flag.
2. Queries are generated by an LLM in the document's own language, so no step
   depends on Latin capitalisation or on "." ending a sentence. Both fail on
   part of a 24-language corpus.
3. Relevance is judged by an LLM over a pool built from all systems, not by
   assuming the one source document is the only correct answer. Single-target
   scoring silently penalises semantic retrieval, which is the thing under test.
4. Every claim in the verdict is backed by a paired bootstrap test, so the
   report distinguishes a real difference from noise.

Retrievers only ever see the fields the field audit recommends indexing.
Queries are built only from text that is not indexed, so no mode can win by
matching a string it was also handed.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import math
import os
import random
import re
import time

from collections import Counter, defaultdict
from datetime import datetime
from glob import glob
from typing import Any

import numpy as np

from live_search import build_live_client_from_env
from llm_client import build_client_from_env
from stats import describe_comparison, mean_ci, paired_bootstrap, significance_label

# Conventions, not tuning knobs, but exposed as flags anyway.
DEFAULT_TOPK = 10          # "page one"
DEFAULT_RRF_K = 60         # the constant from the original RRF paper

# The two models the platform actually indexes with. Overridable.
DEFAULT_MODELS = {
    "dense_en": {
        "name": "sentence-transformers/msmarco-distilbert-base-tas-b",
        "label": "English (production index: neural_search_index_msmarco_distilbert)",
    },
    "dense_multi": {
        "name": "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2",
        "label": "Multilingual (production index: neural_search_index_mlang_minilm_v1)",
    },
}

# Fallbacks used only when no field audit report can be found.
FALLBACK_INDEX_FIELDS = [
    "title_llm", "subtitle_llm", "description_llm", "keywords_llm",
    "ko_content_flat_summarised", "project_name", "project_acronym",
]

QUERY_TYPE_BLURB = {
    "topical": "the document's most distinctive words - the ordinary case",
    "unseen-vocab": "words that describe the document but appear nowhere in its indexed text",
    "natural": "a real question in the document's own language, written by the LLM",
    "paraphrase": "the document described in different words, avoiding its own vocabulary",
    "cross-lingual": "the same question asked in a different language from the document",
}

_WORD = re.compile(r"\w+", re.UNICODE)

logging.basicConfig(
    level=os.getenv("LOGLEVEL", "INFO"),
    format="%(asctime)s | %(levelname)s | %(message)s",
)
log = logging.getLogger("compare_search_modes")


# ---------------------------------------------------------------- input ----

def tok(text: str) -> list[str]:
    return _WORD.findall(text.lower()) if text else []


def latest_file(folder: str, pattern: str = "*") -> str | None:
    candidates = [p for p in glob(os.path.join(folder, pattern)) if os.path.isfile(p)]
    if not candidates:
        return None
    candidates.sort(key=lambda p: (os.path.getmtime(p), p))
    return candidates[-1]


def load_records(path: str) -> list[dict[str, Any]]:
    t0 = time.time()
    with open(path, "r", encoding="utf-8") as fh:
        first = fh.read(1)
        while first and first.isspace():
            first = fh.read(1)
    if first in ("[", "{"):
        try:
            with open(path, "r", encoding="utf-8") as fh:
                root = json.load(fh)
        except json.JSONDecodeError:
            root = None
        if root is not None:
            if isinstance(root, dict):
                for key in ("docs", "items", "records", "data", "results", "hits"):
                    value = root.get(key)
                    if isinstance(value, list) and value and all(isinstance(x, dict) for x in value):
                        root = value
                        break
            if not isinstance(root, list):
                raise ValueError("Could not find a list of records in the input JSON")
            log.info("Loaded %d records in %.1fs", len(root), time.time() - t0)
            return [r for r in root if isinstance(r, dict)]
    records = []
    with open(path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    log.info("Loaded %d records (JSONL) in %.1fs", len(records), time.time() - t0)
    return records


def flatten_text(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value.strip()
    if isinstance(value, (int, float, bool)):
        return str(value)
    if isinstance(value, dict):
        for key in ("name", "title", "label", "value"):
            if value.get(key):
                return str(value[key]).strip()
        return " ".join(flatten_text(v) for v in value.values()).strip()
    if isinstance(value, (list, tuple, set)):
        return " ".join(flatten_text(v) for v in value).strip()
    return str(value).strip()


def detect_language(text: str) -> str:
    if not text or len(text) < 40:
        return "unknown"
    try:
        from langdetect import DetectorFactory, detect

        DetectorFactory.seed = 0
        return detect(text[:1200])
    except Exception:
        return "unknown"


# ------------------------------------------------- field-list resolution ----

def read_field_audit(reports_dir: str) -> tuple[list[str], str | None]:
    """Take the indexed-field list from the newest field audit report.

    Keeps this experiment and which_fields_to_choose in step instead of
    restating the field policy in two places.
    """
    path = latest_file(reports_dir, "field_audit_*.txt")
    if not path:
        return [], None
    try:
        with open(path, "r", encoding="utf-8") as fh:
            for line in fh:
                if line.startswith("Full-text fields"):
                    _, _, rhs = line.partition(":")
                    fields = [f.strip() for f in rhs.split(",") if f.strip() and f.strip() != "-"]
                    if fields:
                        return fields, os.path.basename(path)
    except OSError:
        pass
    return [], None


def derive_held_out_fields(
    records: list[dict[str, Any]],
    index_fields: list[str],
    min_avg_words: float,
    max_fields: int,
) -> list[str]:
    """Text-bearing fields that are NOT indexed, ranked by how much text they carry.

    Derived rather than listed, so the experiment still has a query source if
    the field policy changes.
    """
    indexed = set(index_fields)
    stats: dict[str, list[int]] = defaultdict(list)
    sample = records[: min(len(records), 400)]
    for record in sample:
        for key, value in record.items():
            if key in indexed or key.startswith(("_", "@")):
                continue
            lowered = key.lower()
            if any(bit in lowered for bit in ("hash", "_fp", "fingerprint", "url", "doi", "id")):
                continue
            text = flatten_text(value)
            if text:
                stats[key].append(len(text.split()))
    scored = [
        (key, sum(lengths) / len(lengths))
        for key, lengths in stats.items()
        if len(lengths) >= max(3, 0.2 * len(sample))
    ]
    scored = [(k, avg) for k, avg in scored if avg >= min_avg_words]
    scored.sort(key=lambda kv: -kv[1])
    return [k for k, _ in scored[:max_fields]]


# ------------------------------------------- corpus-derived stopwords ------

def derive_stopwords(
    doc_tokens: list[list[str]],
    doc_langs: list[str],
    df_ratio: float,
    min_docs: int,
) -> tuple[dict[str, set[str]], set[str]]:
    """Terms that are too common to carry meaning, computed per language.

    A hand-written stopword list can only cover the languages whoever wrote it
    happened to know. On a 24-language corpus that quietly cleans queries in
    some languages and not others, which biases exactly the comparison this
    script exists to make. Document frequency treats every language alike.
    """
    by_lang: dict[str, list[list[str]]] = defaultdict(list)
    for tokens, lang in zip(doc_tokens, doc_langs):
        by_lang[lang].append(tokens)

    per_lang: dict[str, set[str]] = {}
    for lang, docs in by_lang.items():
        if lang == "unknown" or len(docs) < min_docs:
            continue
        df = Counter()
        for tokens in docs:
            df.update(set(tokens))
        n = len(docs)
        per_lang[lang] = {term for term, count in df.items() if count / n > df_ratio}

    df_all = Counter()
    for tokens in doc_tokens:
        df_all.update(set(tokens))
    n_all = max(1, len(doc_tokens))
    global_stop = {term for term, count in df_all.items() if count / n_all > df_ratio}
    return per_lang, global_stop


# ----------------------------------------------------------------- bm25 ----

class Bm25Index:
    """Same BM25 formulation as which_fields_to_choose/analyse_fields.py.

    A deliberate self-contained copy: this workspace keeps service folders
    independent rather than importing across them.
    """

    def __init__(self, docs_tokens: list[list[str]], k1: float = 1.2, b: float = 0.75) -> None:
        self.n_docs = len(docs_tokens)
        self.k1, self.b = k1, b
        df = Counter()
        dl = np.array([len(t) for t in docs_tokens], dtype=float)
        for tokens in docs_tokens:
            if tokens:
                df.update(set(tokens))
        self.idf = {
            term: math.log((self.n_docs - df[term] + 0.5) / (df[term] + 0.5) + 1.0)
            for term in df
        }
        avgdl = float(dl.mean()) if self.n_docs else 0.0
        self.den_vec = k1 * (1 - b + b * (dl / (avgdl or 1.0))) + 1e-12

        postings_docs: dict[str, list[int]] = defaultdict(list)
        postings_tfs: dict[str, list[int]] = defaultdict(list)
        for doc_id, tokens in enumerate(docs_tokens):
            if not tokens:
                continue
            for term, freq in Counter(tokens).items():
                postings_docs[term].append(doc_id)
                postings_tfs[term].append(freq)
        self.postings = {
            term: (
                np.fromiter(ids, dtype=np.int32, count=len(ids)),
                np.fromiter(postings_tfs[term], dtype=np.float64, count=len(ids)),
            )
            for term, ids in postings_docs.items()
        }
        self.empty = not self.postings

    def rank(self, query_tokens: list[str], k: int) -> list[int]:
        if not query_tokens or self.empty:
            return []
        scores = np.zeros(self.n_docs, dtype=np.float64)
        for term in set(query_tokens):
            weight = self.idf.get(term)
            hit = self.postings.get(term)
            if weight is None or hit is None:
                continue
            ids, tfs = hit
            scores[ids] += weight * ((tfs * (self.k1 + 1.0)) / (tfs + self.den_vec[ids]))
        nz = np.flatnonzero(scores > 0.0)
        if nz.size == 0:
            return []
        order = np.argsort(-scores[nz], kind="stable")[:k]
        return nz[order].tolist()


# ---------------------------------------------------------------- dense ----

def embed(texts: list[str], model_name: str, cache_dir: str, tag: str, batch_size: int = 32) -> np.ndarray:
    from sentence_transformers import SentenceTransformer

    fingerprint = hashlib.sha1(
        (model_name + "\x00" + "\x00".join(texts)).encode("utf-8", "ignore")
    ).hexdigest()[:16]
    os.makedirs(cache_dir, exist_ok=True)
    cache_path = os.path.join(cache_dir, f"{tag}_{fingerprint}.npy")
    if os.path.exists(cache_path):
        log.info("  [%s] reusing cached embeddings", tag)
        return np.load(cache_path)

    t0 = time.time()
    model = SentenceTransformer(model_name, device="cpu")
    vectors = model.encode(
        texts, batch_size=batch_size, convert_to_numpy=True,
        normalize_embeddings=True, show_progress_bar=False,
    ).astype(np.float32)
    log.info("  [%s] encoded %d texts in %.0fs", tag, len(texts), time.time() - t0)
    np.save(cache_path, vectors)
    return vectors


def dense_rank(query_vecs: np.ndarray, doc_vecs: np.ndarray, k: int) -> list[list[int]]:
    rankings = []
    k = min(k, doc_vecs.shape[0])
    for start in range(0, len(query_vecs), 256):
        sims = query_vecs[start:start + 256] @ doc_vecs.T
        top = np.argpartition(-sims, k - 1, axis=1)[:, :k]
        for row, cand in zip(sims, top):
            rankings.append(cand[np.argsort(-row[cand], kind="stable")].tolist())
    return rankings


def rrf_fuse(rankings: list[list[int]], k: int, rrf_k: int) -> list[int]:
    scores: dict[int, float] = defaultdict(float)
    for ranking in rankings:
        for rank, doc_id in enumerate(ranking, start=1):
            scores[doc_id] += 1.0 / (rrf_k + rank)
    return [d for d, _ in sorted(scores.items(), key=lambda kv: (-kv[1], kv[0]))[:k]]


# -------------------------------------------------------------- queries ----

def build_corpus(records: list[dict[str, Any]], index_fields: list[str], held_out_fields: list[str]):
    indexed, held_out = [], []
    for record in records:
        indexed.append(" ".join(t for t in (flatten_text(record.get(f)) for f in index_fields) if t))
        held_out.append(" ".join(t for t in (flatten_text(record.get(f)) for f in held_out_fields) if t))
    return indexed, held_out


def statistical_queries(
    target_ids: list[int],
    indexed: list[str],
    held_tokens: list[list[str]],
    idf: dict[str, float],
    stop_per_lang: dict[str, set[str]],
    global_stop: set[str],
    doc_langs: list[str],
    terms_per_query: int,
) -> list[dict[str, Any]]:
    """The two query types that need no model: most-distinctive terms, and the
    subset of those that the indexed text does not contain."""
    queries: list[dict[str, Any]] = []
    for idx in target_ids:
        stop = stop_per_lang.get(doc_langs[idx], global_stop)
        counts = Counter(
            t for t in held_tokens[idx]
            if len(t) > 2 and t not in stop and not t.isdigit()
        )
        if not counts:
            continue
        ranked = sorted(counts.items(), key=lambda kv: (-(kv[1] * idf.get(kv[0], 0.0)), kv[0]))
        topical = [t for t, _ in ranked[:terms_per_query]]
        if topical:
            queries.append({"target": idx, "type": "topical", "text": " ".join(topical)})
        indexed_tokens = set(tok(indexed[idx]))
        unseen = [t for t, _ in ranked if t not in indexed_tokens][:terms_per_query]
        if len(unseen) >= 4:
            queries.append({"target": idx, "type": "unseen-vocab", "text": " ".join(unseen)})
    return queries


QUERY_PROMPT = """You are helping evaluate a search engine for an EU agricultural
knowledge platform. Below is an excerpt from one document.

Return ONLY a JSON object, no commentary:
{{
  "lang": "<ISO 639-1 code of the excerpt's language>",
  "question": "<one natural question a farmer or advisor would type into a search box to find this document, written IN THE EXCERPT'S OWN LANGUAGE, 6-15 words>",
  "question_other_lang": "<the same question translated into {other_language}>",
  "other_lang": "{other_code}",
  "paraphrase": "<describe what this document is about in 8-15 words, in English, WITHOUT reusing its distinctive technical terms - use everyday synonyms instead>"
}}

EXCERPT:
{excerpt}"""

# Chosen to span scripts and families actually present in EU-FarmBook content.
CROSS_LANGUAGE_CHOICES = [
    ("English", "en"), ("French", "fr"), ("Spanish", "es"), ("German", "de"),
    ("Italian", "it"), ("Polish", "pl"), ("Dutch", "nl"), ("Greek", "el"),
]


def llm_queries(
    client,
    target_ids: list[int],
    held_out: list[str],
    doc_langs: list[str],
    excerpt_chars: int,
    workers: int,
    seed: int,
) -> list[dict[str, Any]]:
    """Natural, paraphrase and cross-lingual queries, one LLM call per document."""
    rng = random.Random(seed)
    jobs = []
    for idx in target_ids:
        doc_lang = doc_langs[idx]
        choices = [c for c in CROSS_LANGUAGE_CHOICES if c[1] != doc_lang] or CROSS_LANGUAGE_CHOICES
        other_name, other_code = rng.choice(choices)
        jobs.append((idx, other_name, other_code))

    def worker(job):
        idx, other_name, other_code = job
        prompt = QUERY_PROMPT.format(
            other_language=other_name,
            other_code=other_code,
            excerpt=held_out[idx][:excerpt_chars],
        )
        return idx, client.complete_json(prompt, max_tokens=320)

    results = client.map_concurrent(jobs, worker, workers=workers, label="queries")

    queries: list[dict[str, Any]] = []
    for item in results:
        if not item:
            continue
        idx, data = item
        if not isinstance(data, dict):
            continue
        question = (data.get("question") or "").strip()
        other = (data.get("question_other_lang") or "").strip()
        paraphrase = (data.get("paraphrase") or "").strip()
        detected = (data.get("lang") or "").strip().lower()[:2] or doc_langs[idx]
        other_code = (data.get("other_lang") or "").strip().lower()[:2]
        if len(question.split()) >= 3:
            queries.append({"target": idx, "type": "natural", "text": question, "query_lang": detected})
        if len(paraphrase.split()) >= 4:
            queries.append({"target": idx, "type": "paraphrase", "text": paraphrase, "query_lang": "en"})
        if len(other.split()) >= 3 and other_code and other_code != detected:
            queries.append({
                "target": idx, "type": "cross-lingual", "text": other,
                "query_lang": other_code, "doc_lang": detected,
            })
    return queries


# -------------------------------------------------------------- judging ----

JUDGE_PROMPT = """You are judging search results for an EU agricultural knowledge platform.

QUERY: {query}

Below are candidate documents. For each, decide how well it answers the query.

Grades:
3 = directly answers the query; this is what the user wanted
2 = substantially about the query's topic and clearly useful
1 = related but only marginally useful
0 = not relevant

Return ONLY a JSON object mapping each candidate number to its grade, e.g.
{{"1": 3, "2": 0, "3": 1}}

CANDIDATES:
{candidates}"""


def judge_pool(
    client,
    queries: list[dict[str, Any]],
    pools: list[list[int]],
    doc_snippets: list[str],
    workers: int,
    batch_size: int,
) -> list[dict[int, int]]:
    """Grade every (query, pooled document) pair with the LLM.

    Standard pooling: the union of what all systems returned is judged, so no
    system is scored against a relevance set built from its own output. This
    replaces "only the source document counts", which penalises any retriever
    that surfaces other genuinely relevant documents.
    """
    jobs = []
    for qi, (query, pool) in enumerate(zip(queries, pools)):
        for start in range(0, len(pool), batch_size):
            jobs.append((qi, pool[start:start + batch_size]))

    def worker(job):
        qi, doc_ids = job
        candidates = "\n\n".join(
            f"[{n}] {doc_snippets[d]}" for n, d in enumerate(doc_ids, start=1)
        )
        data = client.complete_json(
            JUDGE_PROMPT.format(query=queries[qi]["text"], candidates=candidates),
            max_tokens=260,
        )
        grades: dict[int, int] = {}
        if isinstance(data, dict):
            for key, value in data.items():
                try:
                    n = int(re.sub(r"\D", "", str(key)))
                    grade = int(value)
                except (TypeError, ValueError):
                    continue
                if 1 <= n <= len(doc_ids):
                    grades[doc_ids[n - 1]] = max(0, min(3, grade))
        return qi, grades

    results = client.map_concurrent(jobs, worker, workers=workers, label="judging")

    qrels: list[dict[int, int]] = [dict() for _ in queries]
    for item in results:
        if not item:
            continue
        qi, grades = item
        qrels[qi].update(grades)
    return qrels


# -------------------------------------------------------------- metrics ----

def per_query_rr(rankings: list[list[int]], targets: list[int], k: int) -> np.ndarray:
    out = np.zeros(len(rankings))
    for i, (ranking, target) in enumerate(zip(rankings, targets)):
        for rank, doc_id in enumerate(ranking[:k], start=1):
            if doc_id == target:
                out[i] = 1.0 / rank
                break
    return out


def per_query_hit(rankings: list[list[int]], targets: list[int], k: int) -> np.ndarray:
    return np.array([1.0 if t in r[:k] else 0.0 for r, t in zip(rankings, targets)])


def per_query_ndcg(rankings: list[list[int]], qrels: list[dict[int, int]], k: int) -> np.ndarray:
    out = np.zeros(len(rankings))
    for i, (ranking, rels) in enumerate(zip(rankings, qrels)):
        if not rels:
            continue
        dcg = sum(
            (2 ** rels.get(doc_id, 0) - 1) / math.log2(rank + 1)
            for rank, doc_id in enumerate(ranking[:k], start=1)
        )
        ideal = sorted(rels.values(), reverse=True)[:k]
        idcg = sum((2 ** g - 1) / math.log2(r + 1) for r, g in enumerate(ideal, start=1))
        out[i] = dcg / idcg if idcg > 0 else 0.0
    return out


def summarise(scores: np.ndarray, seed: int) -> dict[str, float]:
    mean, lo, hi = mean_ci(scores, seed=seed)
    return {"mean": mean, "lo": lo, "hi": hi, "n": int(scores.size)}


# ---------------------------------------------------------------- report ----

def fmt(row: dict[str, float]) -> str:
    return f"{row['mean']:.4f} [{row['lo']:.4f}, {row['hi']:.4f}]"


def build_report(ctx: dict[str, Any]) -> str:
    L: list[str] = []
    systems = ctx["systems"]
    scores = ctx["scores"]
    judged = ctx["judged"]

    L.append("=== SETUP ===")
    L.append(f"Input file            : {ctx['input']}")
    L.append(f"Documents in corpus   : {ctx['n_docs']}")
    L.append(f"Queries generated     : {ctx['n_queries']}  ({', '.join(ctx['type_counts'])})")
    L.append(f"Indexed fields        : {', '.join(ctx['index_fields'])}")
    L.append(f"  source              : {ctx['index_source']}")
    L.append(f"Held out for queries  : {', '.join(ctx['held_out_fields'])}")
    L.append(f"Stopwords             : derived from the corpus, {ctx['n_stop_langs']} languages "
             f"(terms in >{ctx['df_ratio']:.0%} of that language's documents)")
    L.append(f"Run time              : {ctx['elapsed']:.0f}s")
    L.append("")
    L.append("Systems compared:")
    for key, label in systems.items():
        L.append(f"  {key:16} {label}")
    L.append("")
    L.append(f"LLM (queries + judging): {ctx['llm_model']}")
    L.append(f"  {ctx['llm_usage']}")
    if ctx.get("live_usage"):
        L.append(f"Live endpoint: {ctx['live_usage']}")

    L.append("")
    L.append("=== HEADLINE ===")
    L.append("Two scorings are reported because they answer different questions.")
    L.append("")
    L.append("KNOWN-ITEM (all queries): did the system find the exact document the")
    L.append("query was written from? Strict, and unfair to any system that surfaces")
    L.append("other genuinely relevant documents.")
    L.append("")
    L.append(f"  {'system':16} {'MRR@' + str(ctx['topk']):>26} {'Hit@1':>22}")
    for key in systems:
        L.append(f"  {key:16} {fmt(scores['known'][key]['mrr']):>26} {fmt(scores['known'][key]['hit1']):>22}")

    if judged:
        L.append("")
        L.append("JUDGED (LLM-graded, pooled): how good is the whole top-10, where every")
        L.append("candidate any system returned was graded 0-3 for relevance. This is the")
        L.append("fairer comparison and the one the verdict is based on.")
        L.append("")
        L.append(f"  {'system':16} {'nDCG@' + str(ctx['topk']):>26}")
        for key in systems:
            L.append(f"  {key:16} {fmt(scores['judged'][key]['ndcg']):>26}")
        L.append("")
        L.append(f"  judged queries: {ctx['n_judged']}   graded pairs: {ctx['n_graded']}")
        L.append(f"  mean relevant (grade>0) per query: {ctx['mean_relevant']:.1f}")

    L.append("")
    L.append("=== IS THE DIFFERENCE REAL? ===")
    L.append("Paired bootstrap over queries, 95% CI. Systems run on identical queries,")
    L.append("so the comparison is paired.")
    for metric_label, pairs in ctx["significance"].items():
        L.append("")
        L.append(f"{metric_label}:")
        for line in pairs:
            L.append(f"  {line}")

    L.append("")
    L.append("=== BY QUERY TYPE ===")
    for qtype, rows in ctx["by_type"].items():
        L.append("")
        L.append(f"{qtype}  ({rows['n']} queries) - {QUERY_TYPE_BLURB.get(qtype, '')}")
        for key in systems:
            extra = ""
            if judged and qtype in ctx["by_type_judged"]:
                jr = ctx["by_type_judged"][qtype].get(key)
                if jr:
                    extra = f"   nDCG {jr['mean']:.4f}"
            L.append(f"  {key:16} MRR {rows[key]['mean']:.4f}{extra}")

    if ctx["by_lang"]:
        L.append("")
        L.append("=== BY LANGUAGE RELATIONSHIP ===")
        L.append("cross-language = the query was asked in a different language from the")
        L.append("document. Keyword matching cannot serve this case at all.")
        for bucket, rows in sorted(ctx["by_lang"].items(), key=lambda kv: -kv[1]["n"]):
            if rows["n"] < ctx["min_bucket"]:
                continue
            L.append("")
            L.append(f"{bucket}  ({rows['n']} queries)")
            for key in systems:
                L.append(f"  {key:16} MRR {rows[key]['mean']:.4f}")

    if ctx["router"]:
        L.append("")
        L.append("=== THE LIVE SYSTEM'S INTENT ROUTER ===")
        L.append("The deployed endpoint decides per query whether to use the semantic half.")
        L.append("This is what it decided, and how well it did.")
        L.append("")
        L.append(f"  {'router mode':24} {'semantic?':10} {'queries':>8} {'live MRR':>10} {'best local':>12}")
        for mode, row in sorted(ctx["router"].items(), key=lambda kv: -kv[1]["n"]):
            L.append(
                f"  {str(mode)[:23]:24} {str(row['use_semantic']):10} {row['n']:8} "
                f"{row['live_mrr']:10.4f} {row['best_local']:12.4f}"
            )
        L.append("")
        for line in ctx["router_findings"]:
            L.append(f"  {line}")

    L.append("")
    L.append("=== DO THE SYSTEMS FIND THE SAME DOCUMENTS? ===")
    for line in ctx["complement_lines"]:
        L.append(f"  {line}")

    L.append("")
    L.append("=== VERDICT ===")
    for line in ctx["verdict"]:
        L.append(line)

    L.append("")
    L.append("=== WHAT THIS TEST CANNOT TELL YOU ===")
    L.append("  - Queries are written by an LLM from each document, not observed from real")
    L.append("    users. They are realistic in shape and language but not in intent.")
    L.append("  - Relevance is graded by an LLM. It is consistent and cheap, but it is not")
    L.append("    a domain expert and has not been validated against human agreement here.")
    L.append("  - The local arms truncate documents to each model's context window; the live")
    L.append("    system chunks them properly. Long documents therefore do better live.")
    L.append("  - The local corpus is a sample; the live endpoint searches the whole index,")
    L.append("    which is a harder task. Judged scoring absorbs most of this, known-item")
    L.append("    scoring does not.")
    return "\n".join(L)


# ------------------------------------------------------------------ main ----

def parse_args() -> argparse.Namespace:
    base = os.path.dirname(os.path.abspath(__file__))
    p = argparse.ArgumentParser(description="Compare keyword, semantic and the live hybrid.")
    p.add_argument("--input", help="JSON/JSONL export. Defaults to newest in ../input")
    p.add_argument("--limit", type=int, default=4000, help="Documents in the local corpus (0 = all)")
    p.add_argument("--queries", type=int, default=250, help="Documents to draw queries from")
    p.add_argument("--judge-queries", type=int, default=250, help="Queries to LLM-judge (0 = none)")
    p.add_argument("--seed", type=int, default=13)
    p.add_argument("--topk", type=int, default=DEFAULT_TOPK)
    p.add_argument("--rrf-k", type=int, default=DEFAULT_RRF_K)
    p.add_argument("--terms-per-query", type=int, default=8)
    p.add_argument("--stopword-df", type=float, default=0.25,
                   help="A term in more than this share of a language's docs is a stopword")
    p.add_argument("--stopword-min-docs", type=int, default=40)
    p.add_argument("--held-out-min-words", type=float, default=5.0)
    p.add_argument("--held-out-max-fields", type=int, default=6)
    p.add_argument("--excerpt-chars", type=int, default=1800)
    p.add_argument("--judge-batch", type=int, default=10)
    p.add_argument("--workers", type=int, default=8)
    p.add_argument("--min-bucket", type=int, default=25)
    p.add_argument("--no-llm", action="store_true", help="Statistical queries only, no judging")
    p.add_argument("--no-live", action="store_true", help="Skip the deployed endpoint")
    p.add_argument("--no-english-model", action="store_true", help="Skip the English-only embedder")
    p.add_argument("--index-fields", help="Comma-separated override")
    p.add_argument("--cache-dir", default=os.path.join(base, ".cache"))
    p.add_argument("--output-dir", default=os.path.join(base, "..", "reports"))
    return p.parse_args()


def main() -> None:
    t0 = time.time()
    args = parse_args()
    base = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.abspath(os.path.join(base, ".."))
    workspace = os.path.abspath(os.path.join(repo, ".."))
    reports_dir = os.path.abspath(args.output_dir)

    args.input = args.input or latest_file(os.path.join(repo, "input"))
    if not args.input:
        raise FileNotFoundError("No input file found in ../input")
    log.info("Input: %s", args.input)

    records = load_records(args.input)
    rng = random.Random(args.seed)
    if args.limit and len(records) > args.limit:
        keep = sorted(rng.sample(range(len(records)), args.limit))
        records = [records[i] for i in keep]
        log.info("Sampled %d documents (seed %d)", len(records), args.seed)

    # --- field lists: from the field audit, not restated here ---------------
    if args.index_fields:
        index_fields, index_source = [f.strip() for f in args.index_fields.split(",") if f.strip()], "--index-fields"
    else:
        index_fields, audit_name = read_field_audit(reports_dir)
        index_source = f"field audit {audit_name}" if audit_name else "built-in fallback (no field audit found)"
        if not index_fields:
            index_fields = FALLBACK_INDEX_FIELDS
    index_fields = [f for f in index_fields if any(f in r for r in records[:200])]
    held_out_fields = derive_held_out_fields(records, index_fields, args.held_out_min_words, args.held_out_max_fields)
    log.info("Indexed: %s", ", ".join(index_fields))
    log.info("Held out: %s", ", ".join(held_out_fields))
    if not held_out_fields:
        raise RuntimeError("No held-out text fields found - cannot generate queries fairly")

    indexed, held_out = build_corpus(records, index_fields, held_out_fields)
    n_docs = len(indexed)
    doc_ids = [str(r.get("_id") or r.get("_orig_id") or r.get("@id") or i) for i, r in enumerate(records)]
    id_to_pos = {d: i for i, d in enumerate(doc_ids)}

    log.info("Detecting languages ...")
    doc_langs = [detect_language(t) for t in indexed]

    held_tokens = [tok(t) for t in held_out]
    stop_per_lang, global_stop = derive_stopwords(
        held_tokens, doc_langs, args.stopword_df, args.stopword_min_docs
    )
    log.info("Derived stopwords for %d languages", len(stop_per_lang))

    df = Counter()
    for t in held_tokens:
        if t:
            df.update(set(t))
    idf = {t: math.log((n_docs - c + 0.5) / (c + 0.5) + 1.0) for t, c in df.items()}

    eligible = [i for i, t in enumerate(held_tokens) if len(t) >= 40]
    targets = sorted(rng.sample(eligible, min(args.queries, len(eligible))))

    queries = statistical_queries(
        targets, indexed, held_tokens, idf, stop_per_lang, global_stop, doc_langs, args.terms_per_query
    )

    client = None
    if not args.no_llm:
        client = build_client_from_env(
            [os.path.join(workspace, "farm_assistant_um", ".env"),
             os.path.join(workspace, "scout", ".env"),
             os.path.join(repo, ".env")],
            os.path.join(args.cache_dir, "llm"),
        )
        log.info("LLM: %s", client.model)
        queries += llm_queries(client, targets, held_out, doc_langs, args.excerpt_chars, args.workers, args.seed)

    if not queries:
        raise RuntimeError("No queries generated")
    for q in queries:
        q.setdefault("query_lang", detect_language(q["text"]))
    log.info("Generated %d queries", len(queries))

    query_texts = [q["text"] for q in queries]
    q_targets = [q["target"] for q in queries]

    # --- systems ------------------------------------------------------------
    systems: dict[str, str] = {}
    rankings: dict[str, list[list[int]]] = {}

    log.info("BM25 over %d documents ...", n_docs)
    bm25 = Bm25Index([tok(t) for t in indexed])
    rankings["local_bm25"] = [bm25.rank(tok(t), args.topk) for t in query_texts]
    systems["local_bm25"] = "Pure keyword search (BM25), local"

    model_keys = ["dense_multi"] + ([] if args.no_english_model else ["dense_en"])
    for key in model_keys:
        cfg = DEFAULT_MODELS[key]
        log.info("Embedding with %s ...", key)
        dv = embed(indexed, cfg["name"], args.cache_dir, f"docs_{key}")
        qv = embed(query_texts, cfg["name"], args.cache_dir, f"q_{key}")
        rankings[f"local_{key}"] = dense_rank(qv, dv, args.topk)
        systems[f"local_{key}"] = f"Pure semantic, {cfg['label']}"

    best_local_dense = max(
        (k for k in rankings if k.startswith("local_dense")),
        key=lambda k: per_query_rr(rankings[k], q_targets, args.topk).mean(),
    )
    rankings["local_hybrid"] = [
        rrf_fuse([rankings["local_bm25"][i], rankings[best_local_dense][i]], args.topk, args.rrf_k)
        for i in range(len(queries))
    ]
    systems["local_hybrid"] = f"RRF fusion of BM25 + {best_local_dense.replace('local_', '')}"

    live_client = None
    live_meta: list[dict[str, Any]] = []
    live_snippets: dict[str, str] = {}
    if not args.no_live:
        live_client = build_live_client_from_env(
            {"fa": os.path.join(workspace, "farm_assistant_um", ".env"),
             "scout": os.path.join(workspace, "scout", ".env")},
            os.path.join(args.cache_dir, "live"),
        )
    if live_client:
        log.info("Querying the deployed endpoint ...")
        from concurrent.futures import ThreadPoolExecutor
        with ThreadPoolExecutor(max_workers=min(4, args.workers)) as pool:
            live_raw = list(pool.map(lambda t: live_client.search(t, size=args.topk), query_texts))
        live_rank: list[list[int]] = []
        for res in live_raw:
            live_meta.append(res)
            live_snippets.update(res.get("snippets") or {})
            live_rank.append([id_to_pos[i] for i in res["ids"] if i in id_to_pos])
        rankings["live_hybrid"] = live_rank
        systems["live_hybrid"] = "The deployed endpoint (neural_search_relevant, mlang_minilm)"
        log.info("Live: %s", live_client.usage_summary())

    # --- known-item scoring -------------------------------------------------
    known = {
        key: {
            "mrr": summarise(per_query_rr(r, q_targets, args.topk), args.seed),
            "hit1": summarise(per_query_hit(r, q_targets, 1), args.seed),
        }
        for key, r in rankings.items()
    }
    rr_vectors = {k: per_query_rr(r, q_targets, args.topk) for k, r in rankings.items()}

    # --- LLM-judged pooled scoring -----------------------------------------
    judged = False
    judged_scores: dict[str, dict[str, Any]] = {}
    ndcg_vectors: dict[str, np.ndarray] = {}
    n_graded = 0
    mean_relevant = 0.0
    judge_idx: list[int] = []
    if client and args.judge_queries:
        judge_idx = sorted(rng.sample(range(len(queries)), min(args.judge_queries, len(queries))))
        snippets = [
            (indexed[i][:600] if indexed[i] else held_out[i][:600]) for i in range(n_docs)
        ]
        pools: list[list[int]] = []
        for qi in judge_idx:
            pool: list[int] = []
            for key in rankings:
                for d in rankings[key][qi][: args.topk]:
                    if d not in pool:
                        pool.append(d)
            if q_targets[qi] not in pool:
                pool.append(q_targets[qi])
            pools.append(pool)
        log.info("Judging %d queries, %d pooled pairs ...", len(judge_idx), sum(len(p) for p in pools))
        qrels_sub = judge_pool(client, [queries[i] for i in judge_idx], pools, snippets,
                               args.workers, args.judge_batch)
        n_graded = sum(len(g) for g in qrels_sub)
        rel_counts = [sum(1 for v in g.values() if v > 0) for g in qrels_sub]
        mean_relevant = sum(rel_counts) / max(1, len(rel_counts))
        judged = n_graded > 0
        if judged:
            for key in rankings:
                vec = per_query_ndcg([rankings[key][i] for i in judge_idx], qrels_sub, args.topk)
                ndcg_vectors[key] = vec
                judged_scores[key] = {"ndcg": summarise(vec, args.seed)}

    # --- significance -------------------------------------------------------
    significance: dict[str, list[str]] = {}
    keys = list(systems)
    known_pairs = []
    for i, a in enumerate(keys):
        for b in keys[i + 1:]:
            known_pairs.append(describe_comparison(a, b, paired_bootstrap(rr_vectors[a], rr_vectors[b], seed=args.seed)))
    significance[f"Known-item MRR@{args.topk}"] = known_pairs
    if judged:
        jp = []
        for i, a in enumerate(keys):
            for b in keys[i + 1:]:
                jp.append(describe_comparison(a, b, paired_bootstrap(ndcg_vectors[a], ndcg_vectors[b], seed=args.seed)))
        significance[f"LLM-judged nDCG@{args.topk}"] = jp

    # --- breakdowns ---------------------------------------------------------
    by_type: dict[str, Any] = {}
    for qtype in sorted({q["type"] for q in queries}):
        picks = [i for i, q in enumerate(queries) if q["type"] == qtype]
        row: dict[str, Any] = {"n": len(picks)}
        for key in systems:
            row[key] = summarise(rr_vectors[key][picks], args.seed)
        by_type[qtype] = row

    by_type_judged: dict[str, Any] = {}
    if judged:
        pos = {qi: n for n, qi in enumerate(judge_idx)}
        for qtype in by_type:
            picks = [pos[i] for i, q in enumerate(queries) if q["type"] == qtype and i in pos]
            if len(picks) < 5:
                continue
            by_type_judged[qtype] = {k: summarise(ndcg_vectors[k][picks], args.seed) for k in systems}

    by_lang: dict[str, Any] = {}
    for i, q in enumerate(queries):
        ql, dl = q.get("query_lang", "unknown"), doc_langs[q["target"]]
        bucket = "unknown" if "unknown" in (ql, dl) else (
            "cross-language" if ql != dl else ("same-language (en)" if ql == "en" else "same-language (non-en)")
        )
        by_lang.setdefault(bucket, []).append(i)
    by_lang = {
        b: {"n": len(ix), **{k: summarise(rr_vectors[k][ix], args.seed) for k in systems}}
        for b, ix in by_lang.items()
    }

    # --- router analysis ----------------------------------------------------
    router: dict[str, Any] = {}
    router_findings: list[str] = []
    if live_meta:
        groups: dict[Any, list[int]] = defaultdict(list)
        for i, m in enumerate(live_meta):
            # use_semantic here is the SELECTED attempt's, not the profile
            # default: the cascade can reach a semantic attempt after a lexical
            # one returns nothing, and only the selected attempt reflects that.
            groups[(m.get("mode"), m.get("use_semantic"))].append(i)
        local_best_key = max(
            (k for k in systems if k.startswith("local")),
            key=lambda k: rr_vectors[k].mean(),
        )
        for (mode, sem), ix in groups.items():
            if len(ix) < args.min_bucket:
                continue
            router[f"{mode}"] = {
                "use_semantic": sem,
                "n": len(ix),
                "live_mrr": float(rr_vectors["live_hybrid"][ix].mean()),
                "best_local": float(rr_vectors[local_best_key][ix].mean()),
            }
        off = [m for m, r in router.items() if r["use_semantic"] is False]
        for mode in off:
            r = router[mode]
            sem_key = f"local_{best_local_dense.replace('local_', '')}" if not best_local_dense.startswith("local_") else best_local_dense
            ix = [i for i, m in enumerate(live_meta) if m.get("mode") == mode]
            sem_mrr = float(rr_vectors[best_local_dense][ix].mean()) if ix else 0.0
            lex_mrr = float(rr_vectors["local_bm25"][ix].mean()) if ix else 0.0
            if sem_mrr > lex_mrr:
                router_findings.append(
                    f"On '{mode}' queries the router disables semantic, yet pure semantic "
                    f"scores {sem_mrr:.4f} against pure keyword {lex_mrr:.4f} on the same queries."
                )
        if not router_findings:
            router_findings.append("The router's on/off decisions are consistent with the local measurements.")

    # --- complementarity ----------------------------------------------------
    complement_lines: list[str] = []
    lex, sem = "local_bm25", best_local_dense
    both = only_l = only_s = neither = 0
    for i, t in enumerate(q_targets):
        l = t in rankings[lex][i][: args.topk]
        s = t in rankings[sem][i][: args.topk]
        both += l and s
        only_l += l and not s
        only_s += s and not l
        neither += not l and not s
    total = max(1, both + only_l + only_s + neither)
    complement_lines.append(f"found by both            {both:6} ({100*both/total:5.1f}%)")
    complement_lines.append(f"found by keyword only    {only_l:6} ({100*only_l/total:5.1f}%)")
    complement_lines.append(f"found by semantic only   {only_s:6} ({100*only_s/total:5.1f}%)")
    complement_lines.append(f"found by neither         {neither:6} ({100*neither/total:5.1f}%)")
    unique = (only_l + only_s) / total
    complement_lines.append("")
    complement_lines.append(
        f"{100*unique:.1f}% of successful retrievals came from one mode alone - "
        + ("each reaches documents the other misses, which is the case for running both."
           if unique >= 0.10 else
           "the two largely duplicate each other, so fusion adds little.")
    )

    # --- verdict ------------------------------------------------------------
    metric = "judged" if judged else "known"
    vec = ndcg_vectors if judged else rr_vectors
    ranked = sorted(systems, key=lambda k: vec[k].mean(), reverse=True)
    winner = ranked[0]
    verdict: list[str] = []
    verdict.append(
        f"Best system on {'LLM-judged nDCG' if judged else 'known-item MRR'}: {winner} "
        f"({vec[winner].mean():.4f})."
    )
    runner = ranked[1]
    test = paired_bootstrap(vec[winner], vec[runner], seed=args.seed)
    verdict.append(f"  vs {runner}: {describe_comparison(winner, runner, test)}")
    verdict.append("")
    if unique >= 0.10:
        verdict.append("KEYWORD OR SEMANTIC? Neither alone. The two retrieve materially different")
        verdict.append("documents, so the question is how to combine them, not which to pick.")
    else:
        verdict.append("KEYWORD OR SEMANTIC? The two largely agree on this corpus; the choice")
        verdict.append("matters less than the field selection and the ranking configuration.")
    verdict.append("")
    for qtype, rows in by_type.items():
        best = max(systems, key=lambda k: rows[k]["mean"])
        verdict.append(f"  {qtype:15} best: {best} ({rows[best]['mean']:.4f})")

    ctx = {
        "input": args.input, "n_docs": n_docs, "n_queries": len(queries),
        "type_counts": [f"{t}: {by_type[t]['n']}" for t in by_type],
        "index_fields": index_fields, "index_source": index_source,
        "held_out_fields": held_out_fields, "n_stop_langs": len(stop_per_lang),
        "df_ratio": args.stopword_df, "elapsed": time.time() - t0,
        "systems": systems, "scores": {"known": known, "judged": judged_scores},
        "judged": judged, "n_judged": len(judge_idx), "n_graded": n_graded,
        "mean_relevant": mean_relevant, "significance": significance,
        "by_type": by_type, "by_type_judged": by_type_judged, "by_lang": by_lang,
        "router": router, "router_findings": router_findings,
        "complement_lines": complement_lines, "verdict": verdict,
        "topk": args.topk, "min_bucket": args.min_bucket,
        "llm_model": client.model if client else "(not used)",
        "llm_usage": client.usage_summary() if client else "",
        "live_usage": live_client.usage_summary() if live_client else "",
    }
    report = build_report(ctx)
    print(report)

    os.makedirs(reports_dir, exist_ok=True)
    stamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    out = os.path.join(reports_dir, f"search_mode_comparison_{stamp}.txt")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(report + "\n")
    log.info("Wrote report to %s", out)
    log.info("Total elapsed: %.1fs", time.time() - t0)


if __name__ == "__main__":
    main()
